language: objective-c
osx_image: xcode11
xcode_workspace: SUPLA.xcworkspace
xcode_scheme: SUPLA
xcode_destination: platform=iOS Simulator,OS=13,name=iPhone 11

before_install:
  - pod install --repo-update

notifications:
  slack:
    rooms:
      - supla:dauFpwhgEGeyy9ERzqOYeJyY#github
